In [1]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv("C:/Users/System05/Downloads/Stores.csv")

In [5]:
df

     Store ID   Store_Area  Items_Available  Daily_Customer_Count  Store_Sales
0            1        1659             1961                   530        66490
1            2        1461             1752                   210        39820
2            3        1340             1609                   720        54010
3            4        1451             1748                   620        53730
4            5        1770             2111                   450        46620
..         ...         ...              ...                   ...          ...
891        892        1582             1910                  1080        66390
892        893        1387             1663                   850        82080
893        894        1200             1436                  1060        76440
894        895        1299             1560                   770        96610
895        896        1174             1429                  1110        54340

[896 rows x 5 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 896 entries, 0 to 895
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Store ID              896 non-null    int64
 1   Store_Area            896 non-null    int64
 2   Items_Available       896 non-null    int64
 3   Daily_Customer_Count  896 non-null    int64
 4   Store_Sales           896 non-null    int64
dtypes: int64(5)
memory usage: 35.1 KB

In [7]:
df.isnull().sum().sum()

0

In [8]:
df.describe()

,Store ID,Store_Area,Items_Available,Daily_Customer_Count,Store_Sales
count,896.000000,896.000000,896.000000,896.000000,896.000000
mean,448.500000,1485.409598,1782.035714,786.350446,59351.305804
std,258.797218,250.237011,299.872053,265.389281,17190.741895
min,1.000000,775.000000,932.000000,10.000000,14920.000000
25%,224.750000,1316.750000,1575.500000,600.000000,46530.000000
50%,448.500000,1477.000000,1773.500000,780.000000,58605.000000
75%,672.250000,1653.500000,1982.750000,970.000000,71872.500000
max,896.000000,2229.000000,2667.000000,1560.000000,116320.000000

In [9]:
df.columns

Index(['Store ID ', 'Store_Area', 'Items_Available', 'Daily_Customer_Count',
       'Store_Sales'],
      dtype='object')

In [11]:
df.dtypes

Store ID                int64
Store_Area              int64
Items_Available         int64
Daily_Customer_Count    int64
Store_Sales             int64
dtype: object

In [17]:
df.mean()

Store ID                  448.500000
Store_Area               1485.409598
Items_Available          1782.035714
Daily_Customer_Count      786.350446
Store_Sales             59351.305804
dtype: float64

In [18]:
df.Store_Sales.mean()

59351.30580357143

In [19]:
df.mode()

     Store ID   Store_Area  Items_Available  Daily_Customer_Count  Store_Sales
0            1      1439.0           1858.0                 670.0      54590.0
1            2      1440.0              NaN                   NaN      63540.0
2            3      1458.0              NaN                   NaN          NaN
3            4      1513.0              NaN                   NaN          NaN
4            5      1539.0              NaN                   NaN          NaN
..         ...         ...              ...                   ...          ...
891        892         NaN              NaN                   NaN          NaN
892        893         NaN              NaN                   NaN          NaN
893        894         NaN              NaN                   NaN          NaN
894        895         NaN              NaN                   NaN          NaN
895        896         NaN              NaN                   NaN          NaN

[896 rows x 5 columns]

In [20]:
df.Store_Sales.mode()

0    54590
1    63540
Name: Store_Sales, dtype: int64

In [21]:
df.median()

Store ID                  448.5
Store_Area               1477.0
Items_Available          1773.5
Daily_Customer_Count      780.0
Store_Sales             58605.0
dtype: float64

In [22]:
df.Store_Sales.median()

58605.0

In [23]:
df.min()

Store ID                    1
Store_Area                775
Items_Available           932
Daily_Customer_Count       10
Store_Sales             14920
dtype: int64

In [24]:
df.max()

Store ID                   896
Store_Area                2229
Items_Available           2667
Daily_Customer_Count      1560
Store_Sales             116320
dtype: int64

In [25]:
df.std()

Store ID                  258.797218
Store_Area                250.237011
Items_Available           299.872053
Daily_Customer_Count      265.389281
Store_Sales             17190.741895
dtype: float64

In [28]:
df.groupby(['Items_Available'])['Store_Sales'].mean()

Items_Available
932     42530.0
951     25600.0
1018    77740.0
1050    52540.0
1059    75110.0
         ...
2492    70230.0
2493    51480.0
2617    67080.0
2647    65900.0
2667    87410.0
Name: Store_Sales, Length: 616, dtype: float64

In [29]:
df_u=df.rename(columns= {'Store_Sales k$)':'Sales'},inplace=False)
(df_u.groupby(['Items_Available']).Sales.mean())

AttributeError: 'DataFrameGroupBy' object has no attribute 'Sales'